In [3]:
import re
import pandas as pd
import numpy as np

In [2]:
series=pd.read_csv('Data/tv_shows.csv')

In [3]:
#Unnamed: 0 is the same as index
(series.index==series['Unnamed: 0']).sum()

5611

In [4]:
#type id being kept in case we want to merge series and movies
series.drop('Unnamed: 0', axis=1,inplace=True)

In [5]:
series.rename(columns={'type':'Type'},inplace=True)

In [6]:
series.head()

,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type
0,Breaking Bad,2008,18+,9.5,96%,1,0,0,0,1
1,Stranger Things,2016,16+,8.8,93%,1,0,0,0,1
2,Money Heist,2017,18+,8.4,91%,1,0,0,0,1
3,Sherlock,2010,16+,9.1,78%,1,0,0,0,1
4,Better Call Saul,2015,18+,8.7,97%,1,0,0,0,1

In [7]:
series.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5611 entries, 0 to 5610
Data columns (total 10 columns):
Title              5611 non-null object
Year               5611 non-null int64
Age                3165 non-null object
IMDb               4450 non-null float64
Rotten Tomatoes    1011 non-null object
Netflix            5611 non-null int64
Hulu               5611 non-null int64
Prime Video        5611 non-null int64
Disney+            5611 non-null int64
Type               5611 non-null int64
dtypes: float64(1), int64(6), object(3)
memory usage: 438.4+ KB

In [8]:
movies=pd.read_csv('Data/movies.csv')

In [9]:
#Unnamed: 0 is the same as index
(movies.index==movies['Unnamed: 0']).sum()

16744

In [10]:
#ID the same as index+1
(movies.index+1==movies['ID']).sum()

16744

In [11]:
movies.drop(['Unnamed: 0','ID'],axis=1,inplace=True)

In [12]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16744 entries, 0 to 16743
Data columns (total 15 columns):
Title              16744 non-null object
Year               16744 non-null int64
Age                7354 non-null object
IMDb               16173 non-null float64
Rotten Tomatoes    5158 non-null object
Netflix            16744 non-null int64
Hulu               16744 non-null int64
Prime Video        16744 non-null int64
Disney+            16744 non-null int64
Type               16744 non-null int64
Directors          16018 non-null object
Genres             16469 non-null object
Country            16309 non-null object
Language           16145 non-null object
Runtime            16152 non-null float64
dtypes: float64(2), int64(6), object(7)
memory usage: 1.9+ MB

In [13]:
series.head()

,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type
0,Breaking Bad,2008,18+,9.5,96%,1,0,0,0,1
1,Stranger Things,2016,16+,8.8,93%,1,0,0,0,1
2,Money Heist,2017,18+,8.4,91%,1,0,0,0,1
3,Sherlock,2010,16+,9.1,78%,1,0,0,0,1
4,Better Call Saul,2015,18+,8.7,97%,1,0,0,0,1

In [14]:
movies['Episodes']=1

In [15]:
movies.head()

,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime,Episodes
0,Inception,2010,13+,8.8,87%,1,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0,1
1,The Matrix,1999,18+,8.7,87%,1,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0,1
2,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0,1
3,Back to the Future,1985,7+,8.5,96%,1,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0,1
4,"The Good, the Bad and the Ugly",1966,18+,8.8,97%,1,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0,1

In [16]:
extra_series=pd.read_csv('Data/extra_tv_shows.csv')

In [19]:
full_series=pd.merge(series,extra_series)

In [21]:
full_series.rename(columns={'Genre':'Genres','Creator':'Directors'},inplace=True)

In [26]:
full_series=full_series[movies.columns]

In [27]:
full_series.head()

,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime,Episodes
0,Breaking Bad,2008,18+,9.5,96%,1,0,0,0,1,Vince Gilligan,"Crime,Drama,Thriller",USA,"English,Spanish",49,62.0
1,Stranger Things,2016,16+,8.8,93%,1,0,0,0,1,"Matt Duffer,Ross Duffer","Drama,Fantasy,Horror,Mystery,Sci-Fi,Thriller",USA,"English,Russian",51,33.0
2,Money Heist,2017,18+,8.4,91%,1,0,0,0,1,Álex Pina,"Action,Crime,Mystery,Thriller",Spain,"Spanish,Russian,Serbian,English",70,31.0
3,Sherlock,2010,16+,9.1,78%,1,0,0,0,1,"Mark Gatiss,Steven Moffat","Crime,Drama,Mystery,Thriller","UK,USA",English,88,15.0
4,Better Call Saul,2015,18+,8.7,97%,1,0,0,0,1,"Vince Gilligan,Peter Gould","Crime,Drama",USA,"English,Spanish,Vietnamese",46,63.0

In [28]:
data=pd.concat([movies,full_series],ignore_index=True)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22091 entries, 0 to 22090
Data columns (total 16 columns):
Title              22091 non-null object
Year               22091 non-null int64
Age                10568 non-null object
IMDb               20665 non-null float64
Rotten Tomatoes    6199 non-null object
Netflix            22091 non-null int64
Hulu               22091 non-null int64
Prime Video        22091 non-null int64
Disney+            22091 non-null int64
Type               22091 non-null int64
Directors          21108 non-null object
Genres             21683 non-null object
Country            21529 non-null object
Language           21233 non-null object
Runtime            19521 non-null object
Episodes           21758 non-null float64
dtypes: float64(2), int64(6), object(8)
memory usage: 2.7+ MB

In [31]:
data.iloc[16740:16750]

,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime,Episodes
16740,The Poof Point,2001,7+,4.7,NaN,0,0,0,1,0,Neal Israel,"Comedy,Family,Sci-Fi",United States,English,90,1.0
16741,Sharks of Lost Island,2013,NaN,5.7,NaN,0,0,0,1,0,Neil Gelinas,Documentary,United States,English,NaN,1.0
16742,Man Among Cheetahs,2017,NaN,6.6,NaN,0,0,0,1,0,Richard Slater-Jones,Documentary,United States,English,NaN,1.0
16743,In Beaver Valley,1950,NaN,NaN,NaN,0,0,0,1,0,James Algar,"Documentary,Short,Family",United States,English,32,1.0
16744,Breaking Bad,2008,18+,9.5,96%,1,0,0,0,1,Vince Gilligan,"Crime,Drama,Thriller",USA,"English,Spanish",49,62.0
16745,Stranger Things,2016,16+,8.8,93%,1,0,0,0,1,"Matt Duffer,Ross Duffer","Drama,Fantasy,Horror,Mystery,Sci-Fi,Thriller",USA,"English,Russian",51,33.0
16746,Money Heist,2017,18+,8.4,91%,1,0,0,0,1,Álex Pina,"Action,Crime,Mystery,Thriller",Spain,"Spanish,Russian,Serbian,English",70,31.0
16747,Sherlock,2010,16+,9.1,78%,1,0,0,0,1,"Mark Gatiss,Steven Moffat","Crime,Drama,Mystery,Thriller","UK,USA",English,88,15.0
16748,Better Call Saul,2015,18+,8.7,97%,1,0,0,0,1,"Vince Gilligan,Peter Gould","Crime,Drama",USA,"English,Spanish,Vietnamese",46,63.0
16749,The Office,2005,16+,8.9,81%,1,0,0,0,1,"Greg Daniels,Ricky Gervais,Stephen Merchant",Comedy,USA,English,22,188.0

In [32]:
data.rename({'Directors':'Directors/Creators','Language':'Languages','Country':'Countries'},axis=1,inplace=True)

In [33]:
data['Rotten Tomatoes']=data['Rotten Tomatoes'].apply(lambda x:x if type(x)!=str else x.strip('%'))
data['Rotten Tomatoes']=data['Rotten Tomatoes'].astype(np.float64)

In [34]:
data.Age=data.Age.apply(lambda x:x if type(x)!=str else 0 if re.findall('all',x) else x.strip('+'))
data.Age=data.Age.astype(np.float64)

In [41]:
data.Runtime=data.Runtime.apply(lambda x:x if type(x)!=str else x.replace(',',''))
data.Runtime=data.Runtime.astype(np.float64)

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22091 entries, 0 to 22090
Data columns (total 16 columns):
Title                 22091 non-null object
Year                  22091 non-null int64
Age                   10568 non-null float64
IMDb                  20665 non-null float64
Rotten Tomatoes       6199 non-null float64
Netflix               22091 non-null int64
Hulu                  22091 non-null int64
Prime Video           22091 non-null int64
Disney+               22091 non-null int64
Type                  22091 non-null int64
Directors/Creators    21108 non-null object
Genres                21683 non-null object
Countries             21529 non-null object
Languages             21233 non-null object
Runtime               19521 non-null float64
Episodes              21758 non-null float64
dtypes: float64(5), int64(6), object(5)
memory usage: 2.7+ MB

In [44]:
genres=list(set([y for x in data['Genres'].unique() for y in str(x).split(',')]))
directors=list(set([y for x in data['Directors/Creators'].unique() for y in str(x).split(',')]))
countries=list(set([y for x in data['Countries'].unique() for y in str(x).split(',')]))
languages=list(set([y for x in data['Languages'].unique() for y in str(x).split(',')]))

In [55]:
data.to_csv('Data/full.csv',index=False,)

In [57]:
len(countries)

183

In [56]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22091 entries, 0 to 22090
Data columns (total 16 columns):
Title                 22091 non-null object
Year                  22091 non-null int64
Age                   10568 non-null float64
IMDb                  20665 non-null float64
Rotten Tomatoes       6199 non-null float64
Netflix               22091 non-null int64
Hulu                  22091 non-null int64
Prime Video           22091 non-null int64
Disney+               22091 non-null int64
Type                  22091 non-null int64
Directors/Creators    21108 non-null object
Genres                21683 non-null object
Countries             21529 non-null object
Languages             21233 non-null object
Runtime               19521 non-null float64
Episodes              21758 non-null float64
dtypes: float64(5), int64(6), object(5)
memory usage: 2.7+ MB

In [80]:
data.head()

,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors/Creators,Genres,Countries,Languages,Runtime,Episodes
0,Inception,2010,13.0,8.8,87.0,1,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0,1.0
1,The Matrix,1999,18.0,8.7,87.0,1,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0,1.0
2,Avengers: Infinity War,2018,13.0,8.5,84.0,1,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0,1.0
3,Back to the Future,1985,7.0,8.5,96.0,1,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0,1.0
4,"The Good, the Bad and the Ugly",1966,18.0,8.8,97.0,1,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0,1.0

In [177]:
new_data=data.copy()
multicolumns=['Directors/Creators','Genres','Countries','Languages']

In [211]:
#Number of new rows for each index
rows=[]
for i in new_data.index:
    crea=str(new_data.loc[i,'Directors/Creators']).split(',')
    gen=str(new_data.loc[i,'Genres']).split(',')
    con=str(new_data.loc[i,'Countries']).split(',')
    lang=str(new_data.loc[i,'Languages']).split(',')
    row=new_data.copy().loc[i]
    for cr in crea:
        for ge in gen:
            for co in con:
                for la in lang:
                    row.loc[multicolumns[0]]=cr
                    row.loc[multicolumns[1]]=ge
                    row.loc[multicolumns[2]]=co
                    row.loc[multicolumns[3]]=la
                    rows.append(row.copy())
    if i%(int(len(new_data)/100))==0:
        print(f'Done index: {i}')

Done index: 0
Done index: 220
Done index: 440
Done index: 660
Done index: 880
Done index: 1100
Done index: 1320
Done index: 1540
Done index: 1760
Done index: 1980
Done index: 2200
Done index: 2420
Done index: 2640
Done index: 2860
Done index: 3080
Done index: 3300
Done index: 3520
Done index: 3740
Done index: 3960
Done index: 4180
Done index: 4400
Done index: 4620
Done index: 4840
Done index: 5060
Done index: 5280
Done index: 5500
Done index: 5720
Done index: 5940
Done index: 6160
Done index: 6380
Done index: 6600
Done index: 6820
Done index: 7040
Done index: 7260
Done index: 7480
Done index: 7700
Done index: 7920
Done index: 8140
Done index: 8360
Done index: 8580
Done index: 8800
Done index: 9020
Done index: 9240
Done index: 9460
Done index: 9680
Done index: 9900
Done index: 10120
Done index: 10340
Done index: 10560
Done index: 10780
Done index: 11000
Done index: 11220
Done index: 11440
Done index: 11660
Done index: 11880
Done index: 12100
Done index: 12320
Done index: 12540
Done index: 12760
Done index: 12980
Done index: 13200
Done index: 13420
Done index: 13640
Done index: 13860
Done index: 14080
Done index: 14300
Done index: 14520
Done index: 14740
Done index: 14960
Done index: 15180
Done index: 15400
Done index: 15620
Done index: 15840
Done index: 16060
Done index: 16280
Done index: 16500
Done index: 16720
Done index: 16940
Done index: 17160
Done index: 17380
Done index: 17600
Done index: 17820
Done index: 18040
Done index: 18260
Done index: 18480
Done index: 18700
Done index: 18920
Done index: 19140
Done index: 19360
Done index: 19580
Done index: 19800
Done index: 20020
Done index: 20240
Done index: 20460
Done index: 20680
Done index: 20900
Done index: 21120
Done index: 21340
Done index: 21560
Done index: 21780
Done index: 22000

In [212]:
megadata=pd.DataFrame(rows)
megadata.to_csv('Data/extra_full.csv',index=False,)

In [26]:
seperated_genres = data['Genres'].str.get_dummies(',')
print('Done Genres')
seperated_genres.columns=['genre_'+x for x in seperated_genres.columns]
seperated_countries = data['Countries'].str.get_dummies(',')
print('Done Countries')
seperated_countries.columns=['countrie_'+x for x in seperated_countries.columns]
seperated_languages = data['Languages'].str.get_dummies(',')
print('Done Languages')
seperated_languages.columns=['language_'+x for x in seperated_languages.columns]

Done Genres
Done Countries
Done Languages

In [27]:
data=pd.concat([data,seperated_genres,seperated_countries,seperated_languages],axis = 1, sort = False)

In [29]:
data.to_csv('Data/dummies.csv',index=False)